### PR TITLE
Create code_review_test.txt

### PR DESCRIPTION
**Pull request by ms130**
Trying to determine who gets notified about this PR, just the two people randomly assigned, or also the whole R code reviewers team?

### CODE REVIEW

**Comment by richardbright** [comment]
I got a notification despite not getting assigned

**Comment by ms130** [comment]
@moj-analytical-services/r_code_reviewers

**Comment by georginaeaton** [comment]
> I got a notification despite not getting assigned

Same for me too. I think it might be dependent on whether you have your GitHub notifications turned on. Noticed this pull request has also gone through to Karik's draft project board too

**Comment by ms130** [comment]
> I got a notification despite not getting assigned

That's great!

> Same for me too. I think it might be dependent on whether you have your GitHub notifications turned on. Noticed this pull request has also gone through to Karik's draft project board too

@georginaeaton that's a good point about the GitHub notifications. Probably something to mention in the documentation to have them turned on for members. Where do I find Karik's draft project board? Sounds like there is automatic integration between PRs and project boards, which is also very encouraging.

**Pull request closed without merging**
