### PR TITLE
round_expenditure function

### PR DESCRIPTION
**Pull request by markrangan**

### CODE REVIEW

**Review by ms130 — CHANGES_REQUESTED** [review]
It would be good if could try and extend the functionality of format_expenditure, which has a very similar behaviour to round_expenditure, ideally while keeping format_expenditure backwards compatible with how it was previously used (unless you feel changing it is a big improvement to usability).

**Comment by markrangan** [comment]
@ms130 In format_expenditure.R, I'm looking to change the name of the dp argument to digits. This will allow user to round the number to the nearest £10k or £0.1k. This will require me to amend the line that describes the dp variable.

I also want to add an error message if users input a number to the currency argument.

**Comment by markrangan** [comment]
@ms130 I think it'd be a good idea to add these 2 tests:

1. Function gives error if anything other than NULL, m or k is input to the format argument.
2. format_expenditure(4654262.65, format = "k", digits = -2) would give £4700k.

**Comment by markrangan** [comment]
@ms130 Just had a look at your new changes. I don't think there's anything else to add. You can now merge this branch with the dev branch.

**Review by ms130 — APPROVED** [review]

**Pull request merged**
