### PR TITLE
Adding feature to specify path to images folder for PDF arrows

### PR DESCRIPTION
**Pull request by stanley-rudkin-moj**
I found that in applying the `arrow_pdf` (and `arrow_image`) functions that I needed to point to images in a different directory to the one specified. So I thought it would be helpful to enable the user to specify their own path to the images folder (leaving the default unchanged, so hopefully this shouldn't break any existing code!)

### CODE REVIEW

**Comment by stanley-rudkin-moj** [comment]
Sorry, not sure what is going on with the automated checks!

**Comment by ms130** [comment]
Hi @stanley-rudkin-moj , this looks like a good change, may I ask why you've closed the PR? I planned to take a look and to try and fix the automated tests

**Comment by stanley-rudkin-moj** [comment]
Hi Marco - happy for us to reopen it. I just found that I no longer needed this and could see it probably encourages people to use a weirder folder structure. Up to you whether we should include it! Thanks for taking the time to look - definitely not urgent from my point of view.

**Comment by ms130** [comment]
Managed to get the tests working, so will merge this now

**Review by ms130 — APPROVED** [review]

**Pull request merged**
